repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'main']
- repo: local
  hooks:
    - id: unittest
      name: unittest
      entry: python -m unittest discover
      language: system
      description: Run all unittests.
      always_run: true
      types: [python]
      pass_filenames: false
      stages: [commit]
