torch:
  device: 'cpu'

# TODO: fix '\t' sep
prepare_data:
  train_data:
    path: 'tests/data/conll.txt'
    sep:
    lower: true
    verbose: true
  val_data:
    path: 'tests/data/conll.txt'
    sep:
    lower: true
    verbose: true
  test_data:
    path: 'tests/data/conll.txt'
    sep:
    lower: true
    verbose: true
  token2idx:
    min_count: 1
    add_pad: true
    add_unk: true

dataloader:
  preprocess: true
  token_padding: '<PAD>'
  label_padding: 'O'
  percentile: 100
  batch_size: 64

model:
  # TODO: add model architecture
  model:
  # TODO: add pretrained embeddings
  # TODO: add dropout
  embedding:
    embedding_dim: 128
  rnn:
    rnn_unit: nn.LSTM
    hidden_size: 256
    num_layers: 1
    dropout: 0
    bidirectional: true
  # TODO: add attention if needed
  attention:
  # TODO: add linear num layers
  linear:

# TODO: add optimizer type (hardcoded Adam)
optimizer:
  lr: 0.001
  beta_0: 0.9
  beta_1: 0.999
  weight_decay: 0
  amsgrad: false

train:
  n_epoch: 10
  verbose: true

save:
  path_to_folder: 'models/test_main/'
  export_onnx: true